const SET_LOGIN_STATE = 'SET_LOGIN_STATE'
const SET_SCROLL_STATE = 'SET_SCROLL_STATE'
const SET_MESSAGE_STATE = 'SET_MESSAGE_STATE'
const SET_SUBMIT_BOX = 'SET_SUBMIT_BOX'
const SET_PRIZE_STATE = 'SET_PRIZE_STATE'
const SUCCESS_PAGE_STATE = 'SUCCESS_PAGE_STATE'
const SET_LISTEN_SCROLL = 'SET_LISTEN_SCROLL'
const SET_SHORT_OF_GOLD_STATE = 'SET_SHORT_OF_GOLD_STATE'
const SET_SEND_SUCCESS = 'SET_SEND_SUCCESS'
const SET_SIGIN_SUCCESS = 'SET_SIGIN_SUCCESS'
const SET_CREATE_USER_MSG = 'SET_CREATE_USER_MSG'
const SET_PRO_ISSUE_NO = 'SET_PRO_ISSUE_NO'
const SET_HOME_SCROLLY = 'SET_HOME_SCROLLY'
const SET_PAYMONEY = 'SET_PAYMONEY'
const SET_CLECT_STATE = 'SET_CLECT_STATE'
const SET_NAV_MSG = 'SET_NAV_MSG'
const SET_DOWN_LOAD = 'SET_DOWN_LOAD'

export {
  SET_LOGIN_STATE,
  SET_SCROLL_STATE,
  SET_MESSAGE_STATE,
  SET_SUBMIT_BOX,
  SET_PRIZE_STATE,
  SUCCESS_PAGE_STATE,
  SET_LISTEN_SCROLL,
  SET_SHORT_OF_GOLD_STATE,
  SET_SEND_SUCCESS,
  SET_SIGIN_SUCCESS,
  SET_CREATE_USER_MSG,
  SET_PRO_ISSUE_NO,
  SET_HOME_SCROLLY,
  SET_PAYMONEY,
  SET_CLECT_STATE,
  SET_NAV_MSG,
  SET_DOWN_LOAD
}
