const SET_LOGIN_STATE = 'SET_LOGIN_STATE'
const SET_SCROLL_STATE = 'SET_SCROLL_STATE'
const SET_MESSAGE_STATE = 'SET_MESSAGE_STATE'
const SET_SUBMIT_BOX = 'SET_SUBMIT_BOX'
const SET_PRIZE_STATE = 'SET_PRIZE_STATE'
const SUCCESS_PAGE_STATE = 'SUCCESS_PAGE_STATE'
const SET_LISTEN_SCROLL = 'SET_LISTEN_SCROLL'
const SET_SHORT_OF_GOLD_STATE = 'SET_SHORT_OF_GOLD_STATE'
const SET_SEND_SUCCESS = 'SET_SEND_SUCCESS'
const SET_SIGIN_SUCCESS = 'SET_SIGIN_SUCCESS'

export {
  SET_LOGIN_STATE,
  SET_SCROLL_STATE,
  SET_MESSAGE_STATE,
  SET_SUBMIT_BOX,
  SET_PRIZE_STATE,
  SUCCESS_PAGE_STATE,
  SET_LISTEN_SCROLL,
  SET_SHORT_OF_GOLD_STATE,
  SET_SEND_SUCCESS,
  SET_SIGIN_SUCCESS
}
